name: 'ORYX QMK Firmware Compiler Action'
author: 'Phoscur'
description: 'Compiles QMK Firmware from ORYX source'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'settings'  
  color: 'orange'
inputs:
  path:
    description: 'Path to keymap source folder'
    default: '.'
  artifacts_path:
    description: 'Path to output build results'
    default: 'artifacts'
  layout_id:
    description: 'ORYX layout hash ID'
    required: true